# name: CI

# on:
#   push:

# jobs:
#   success:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send message to Telegram
#         uses: ./
#         if: always()
#         with:
#           text: "hello 1\nline2\tTab1 \nğŸ³ğŸ³ğŸ³ğŸ³"
